name       : qt-creator
version    : 16.0.0
release    : 68
source     :
    - https://download.qt.io/official_releases/qtcreator/16.0/16.0.0/qt-creator-opensource-src-16.0.0.tar.xz : 18b4353e68a31c062713008c05ce7f7ee88aaaf56d5ac0c6de579babfb2837da
homepage   : https://doc.qt.io/qtcreator/
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(Qt6Charts)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Quick3D)
    - pkgconfig(Qt6SerialPort)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(Qt6WebSockets)
    - pkgconfig(libdw)
    - pkgconfig(libsecret-1)
    - pkgconfig(yaml-cpp)
    - clang-devel
rundeps    :
    - qt6-base-devel
clang      : yes
environment: |
    if [[ " ${PATH[*]} " =~ "ccache" ]]; then
        export CMAKE_C_COMPILER_LAUNCHER=ccache
        export CMAKE_CXX_COMPILER_LAUNCHER=ccache
    fi
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DCMAKE_INSTALL_LIBDIR=$(basename %libdir%) \
        -DPYTHON_EXECUTABLE=$(which python3) \
        -DQTC_CLANG_BUILDMODE_MATCH=ON \
        -DCLANGTOOLING_LINK_CLANG_DYLIB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
