name       : breeze-gtk-theme
version    : 6.3.4
release    : 123
source     :
    - https://download.kde.org/stable/plasma/6.3.4/breeze-gtk-6.3.4.tar.xz : 6c15981d3c94eb12a9d980ef4cfdb3089823e58343d79d8b2fd346ac6d05566f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt6Core)
    - breeze-devel
    - extra-cmake-modules
    - python3-cairo
    - sassc
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
