name       : qt6-networkauth
version    : 6.8.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtnetworkauth-everywhere-src-6.8.3.tar.xz : 27ee8b7c105a9dd75f1182d8dddc3837b875f1145f05311bca343f0838ef4b49
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 NetworkAuth components
description: |
    Qt Network Authorization provides a set of APIs that enable Qt applications to obtain limited access to online accounts and HTTP services without exposing users' passwords.
builddeps  :
    - pkgconfig(Qt6Core)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
