name       : gnote
version    : '47.2'
release    : 32
source     :
    - https://download.gnome.org/sources/gnote/47/gnote-47.2.tar.xz : 9a60f1692480f64d166d31e6564a0ff248127a598e2ff7f6357dc0b2ec25b168
homepage   : https://gitlab.gnome.org/GNOME/gnote
license    : GPL-3.0-or-later
component  : office.notes
summary    : A simple and easy to use desktop note-taking application
description: |
    Gnote is a simple note-taking application for GNOME desktop environment. It allows you to capture your ideas, link them together using WikiWiki-style links, group together in notebooks and some extra features for everyday use.
optimize   :
    - lto
builddeps  :
    - pkgconfig(glibmm-2.68)
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-4.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
