name       : kicad
version    : 9.0.1
release    : 38
source     :
    - https://github.com/KiCad/kicad-source-mirror/archive/refs/tags/9.0.1.tar.gz : ccb9147b974bf84388328c10fae0f4ae1f2a6a847f98d202dc90c012aa0f382c
homepage   : https://www.kicad.org/
license    : GPL-3.0-or-later
component  : office.scientific
summary    : KiCad is an open source software suite for Electronic Design Automation
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
libsplit   : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(dri)
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(glut)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - pkgconfig(libsecret-1)
    - pkgconfig(odbc)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - libboost-devel
    - ngspice-devel
    - nng-devel
    - opencascade-devel
    - swig
    - wxPython
    - wxwidgets-devel
rundeps    :
    - kicad-footprints
    - kicad-packages3d
    - kicad-symbols
    - kicad-templates
    - ngspice-devel
clang      : yes
setup      : |
    %cmake -B build \
        -DKICAD_USE_EGL=TRUE \
        -DKICAD_SCRIPTING_WXPYTHON=OFF \
        -DKICAD_USE_OCE=OFF \
        -DKICAD_USE_OCC=ON \
        -DKICAD_I18N_UNIX_STRICT_PATH=ON
build      : |
    %make -C build
install    : |
    %make_install -C build
    rm -rf $installdir/usr/share/mimelnk
