name       : plasma-activities-stats
version    : 6.3.4
release    : 28
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-activities-stats-6.3.4.tar.xz : 014bd3eb983dc8e10ff52ed02f8d490562b9d0d623918e9270d9d84aa5b28b4d
homepage   : https://invent.kde.org/plasma/plasma-activities-stats
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : A library for accessing the usage data collected by the activities system.
description: |
    A library for accessing the usage data collected by the activities system.
builddeps  :
    - pkgconfig(Qt6Core)
    - kf6-kconfig-devel
    - plasma-activities-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
