name       : pyicu
version    : '2.12'
release    : 32
source     :
    - https://pypi.io/packages/source/P/PyICU/PyICU-2.12.tar.gz : bd7ab5efa93ad692e6daa29cd249364e521218329221726a113ca3cb281c8611
homepage   : https://gitlab.pyicu.org/main/pyicu
license    : MIT
component  : programming.python
summary    : Python extension wrapping the ICU C++ API
description: |
    A Python extension wrapping IBM’s International Components for Unicode C++ library (ICU).
optimize   : speed
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(python3)
checkdeps  :
    - python-pytest
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
  #    %python3_test
