name       : pyicu
version    : '2.15'
release    : 33
source     :
    - https://pypi.io/packages/source/P/PyICU/PyICU-2.15.tar.gz : 241bf4e73851524af67fea5d94ff60bac83dd98ce3ef6fd6f2c00e07e8476c87
homepage   : https://gitlab.pyicu.org/main/pyicu
license    : MIT
component  : programming.python
summary    : Python extension wrapping the ICU C++ API
description: |
    A Python extension wrapping IBM’s International Components for Unicode C++ library (ICU).
optimize   : speed
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(python3)
checkdeps  :
    - python-pytest
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
  #    %python3_test
