name       : kdecoration
version    : 6.3.4
release    : 118
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kdecoration-6.3.4.tar.xz : b9d049a9f5a6359856e66dbad0769b48189210ad7f8b3e009da2b4ae2813789a
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
clang      : yes
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
