name       : proton-vpn-gtk-app
version    : 4.9.5
release    : 16
source     :
    - https://github.com/ProtonVPN/proton-vpn-gtk-app/archive/refs/tags/v4.9.5.tar.gz : cf121aeb171d9b7b54f870332290033fcc4c98d68edc8cd9417dc5ad708b085b
homepage   : https://protonvpn.com/download-linux
license    : GPL-3.0-or-later
component  : programming.python
summary    : Official ProtonVPN Linux app
description: |
    The Proton VPN GTK app is intended for every Proton VPN service user, it provides full access to all functionalities available to authenticated users, with the user signup process handled on the website.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - libayatana-appindicator
    - libgtk-3
    - libwebkit-gtk
    - python-aiohttp
    - python-bcrypt
    - python-dbus
    - python-distro
    - python-gnupg
    - python-gobject
    - python-jinja
    - python-openssl
    - python-packaging
    - python-proton-core
    - python-proton-keyring-linux
    - python-proton-vpn-core-api
    - python-proton-vpn-local-agent
    - python-proton-vpn-network-manager
    - python-pynacl
    - python-requests
    - python-sentry-sdk
    - python3-cairo
build      : |
    %python3_setup
install    : |
    %python3_install

    # Install desktop file, app icon and appstream metainfo
    install -Dm00644 rpmbuild/SOURCES/protonvpn-app.desktop -t $installdir/usr/share/applications
    install -Dm00644 rpmbuild/SOURCES/proton-vpn-logo.svg -t $installdir/usr/share/icons/hicolor/36x36/apps
    install -Dm00644 rpmbuild/SOURCES/proton-vpn-logo.svg -t $installdir/usr/share/icons/hicolor/scalable/apps
    install -Dm00644 $pkgfiles/com.protonvpn.www.metainfo.xml -t $installdir/usr/share/metainfo
conflicts  :
    - protonvpn-cli
    - protonvpn-gui
