name       : gnome-console
version    : '47.2'
release    : 4
source     :
    - https://download.gnome.org/sources/gnome-console/47/gnome-console-47.2.tar.xz : 363493b2a4ff5cbffa1c6a77278bc68b14f557e78c1f8963d6df9399663e74e5
homepage   : https://apps.gnome.org/Console/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Terminal Emulator
description: |
    A simple user-friendly terminal emulator for the GNOME desktop
optimize   :
    - lto
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(vte-2.91-gtk4)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
