name       : morewaita-icon-theme
version    : '48.1'
release    : 6
source     :
    - https://github.com/somepaulo/MoreWaita/archive/refs/tags/v48.1.tar.gz : e379aee0eec070889b6fbb654c838937d01f25e3867c1575a18fb30a5421a408
homepage   : https://github.com/somepaulo/MoreWaita/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : An expanded Adwaita-styled companion icon theme with extra icons for popular apps to complement Gnome Shell's original icons
description: |
    An Adwaita styled theme with extra icons for popular apps to complement Gnome Shell's original icons. The purpose of this theme is to provide a consistent look and feel with Gnome Shell's design.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
