name       : dino
version    : 0.4.5
release    : 7
source     :
    - https://github.com/dino/dino/releases/download/v0.4.5/dino-0.4.5.tar.gz : 81e3ae7be3a361ac25f06d7c63ee42ef0b646d82253b5339efe0ba3111013b89
homepage   : https://dino.im/
license    : GPL-3.0-or-later
component  : network.im
summary    : Modern XMPP ("Jabber") Chat Client using GTK+/Vala
description: |
    Dino is a modern open-source chat client for the desktop. It focuses on providing a clean and reliable Jabber/XMPP experience while having your privacy in mind.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gpgme)
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgcrypt)
    - pkgconfig(libqrencode)
    - pkgconfig(libsignal-protocol-c)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(libsrtp2)
    - pkgconfig(nice)
    - pkgconfig(sqlite3)
    - pkgconfig(webrtc-audio-processing)
    - gettext
    - vala
setup      : |
    %cmake_ninja -DSOUP_VERSION=3
build      : |
    %ninja_build
install    : |
    %ninja_install
