name       : kicad-templates
version    : 9.0.1
release    : 12
source     :
    - https://gitlab.com/kicad/libraries/kicad-templates/-/archive/9.0.1/kicad-templates-9.0.1.tar.gz : bd3adcfd4ea832c38c1e4ddb3555850905c40c04cc2d5755718b9d3a993c535c
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
