name       : rssguard
version    : 4.8.2
release    : 16
source     :
    - https://github.com/martinrotter/rssguard/archive/refs/tags/4.8.2.tar.gz : d0b991deeb021d6cfb085e0c5df1816b41c35e7e0126ae172af70a20b1944727
license    : GPL-3.0-or-later
homepage   : https://github.com/martinrotter/rssguard
component  : network.news
summary    : Simple (yet powerful) Qt feed reader
description: |
    Simple (yet powerful) Qt feed reader
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6WebEngineWidgets)
    - pkgconfig(dbus-1)
    - pkgconfig(mpv)
    - pkgconfig(sqlite3)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-Solus-default-settings.patch
    %cmake_ninja -DBUILD_WITH_QT6=ON \
                 -DNO_UPDATE_CHECK=ON \
                 -DREVISION_FROM_GIT=OFF \
                 -DUSE_SYSTEM_SQLITE=ON \
                 -DUSE_WEBENGINE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /usr/lib64/librssguard.so
