name       : xiphos
version    : 4.3.1
release    : 31
source     :
    - https://github.com/crosswire/xiphos/releases/download/4.3.1/xiphos-4.3.1.tar.xz : 0c90b2e2112d741e301b4ffa4e1b71e68d59b2d2155d6cb0ec5c875cbc609b9a
homepage   : https://xiphos.org/
license    : GPL-2.0-only
component  : office
summary    : Xiphos is a Bible study application
description: |
    Xiphos is a Bible study application
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(minizip)
    - pkgconfig(rarian)
    - pkgconfig(sword)
    - pkgconfig(uuid)
    - pkgconfig(webkit2gtk-4.1)
    - pkgconfig(yelp-xsl)
    - biblesync-devel
    - desktop-file-utils
    - intltool
    - itstool
    - rarian
    - yelp-tools
setup      : |
    %patch -p1 -i $pkgfiles/https-by-default.patch
    mkdir build && cd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
