name       : kclock
version    : 24.12.3
release    : 19
source     :
    - https://download.kde.org/stable/release-service/24.12.3/src/kclock-24.12.3.tar.xz : 43d326dffd1d0ed9b9efad3e7499690c745d486783e0551db6cc3c0952df15ab
homepage   : https://apps.kde.org/kclock
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Clock app for KDE Plasma
description: |
    A convergent clock for KDE Plasma desktop and mobile
    Features
        - Alarms
        - Stopwatch
        - World Clocks
        - Timers
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kirigami-addons-devel
    - libplasma-devel
rundeps    :
    - kirigami-addons
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/upstream.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
