name       : polkit-kde-agent
version    : 6.3.4
release    : 118
source     :
    - https://download.kde.org/stable/plasma/6.3.4/polkit-kde-agent-1-6.3.4.tar.xz : a797f6e02491a2fc60eda14a75e5e796b56513303c99b7465fd964227e98c4cf
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
