name       : libgedit-tepl
version    : 6.11.0
release    : 4
source     :
    - https://gitlab.gnome.org/World/gedit/libgedit-tepl/-/archive/6.11.0/libgedit-tepl-6.11.0.tar.gz : 086402e42814cebc8903ba4ba89f40d6cfb49d9046b02e74e4ec73e3e40ea8cb
homepage   : https://github.com/gedit-technology/libgedit-tepl
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(icu-io)
    - pkgconfig(libgedit-amtk-5)
    - pkgconfig(libgedit-gfls-1)
    - pkgconfig(libgedit-gtksourceview-300)
    - pkgconfig(libhandy-1)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
replaces   :
    - tepl
    - dbginfo : tepl-dbginfo
    - devel : tepl-devel
