name       : gnucash
version    : '5.10'
release    : 58
source     :
    - https://github.com/Gnucash/gnucash/releases/download/5.10/gnucash-5.10.tar.bz2 : 789d9f3698ee5b86720279a3a3e10e7744210e12c525ae7f03d32fa70407ad93
homepage   : https://www.gnucash.org/
license    : GPL-2.0-or-later
component  : office.finance
summary    : GnuCash is personal and small-business financial-accounting software
description: |
    GnuCash is personal and small-business financial-accounting software. Designed to be easy to use, yet powerful and flexible, GnuCash allows you to track bank accounts, stocks, income and expenses. As quick and intuitive to use as a checkbook register, it is based on professional accounting principles to ensure balanced books and accurate reports.
libsplit   : no
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(bdw-gc)
    - pkgconfig(dbi)
    - pkgconfig(gtest)
    - pkgconfig(guile-2.0)
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(libxslt)
    - pkgconfig(webkit2gtk-4.0)
    - libboost-devel
    - libdbi-drivers
    - swig
setup      : |
    %patch -p1 -i $pkgfiles/0001-fix-actions-icons.patch
    %cmake_ninja -DCOMPILE_GSCHEMAS=NO .
build      : |
    %ninja_build
install    : |
    %ninja_install
