name       : weechat
version    : 4.6.0
release    : 91
source     :
    - https://github.com/weechat/weechat/archive/refs/tags/v4.6.0.tar.gz : 11d4914c5b51482c8ade026c3889b68e0c3e1938a0ce6127e36faba48f76e633
homepage   : https://weechat.org
license    : GPL-3.0-or-later
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant-2)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcjson)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzstd)
    - pkgconfig(lua-5.4)
    - pkgconfig(python3)
    - pkgconfig(ruby-3.2)
    - pkgconfig(tcl)
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON -DENABLE_JAVASCRIPT=OFF -DENABLE_PHP=OFF -DWITH-DEBUG=1
build      : |
    %make
install    : |
    %make_install
