name       : kvantum
version    : 1.1.4
release    : 17
source     :
    - https://github.com/tsujan/Kvantum/releases/download/V1.1.4/Kvantum-1.1.4.tar.xz : 0b47a7081b943a035f8cff66767d00cb134f179f5e24d6ac8362c1f2e4ca2d1b
license    : GPL-3.0-or-later
component  : desktop.theme
homepage   : https://github.com/tsujan/Kvantum
summary    : A Linux SVG-based theme engine for Qt5/Qt6 and KDE
description: |
    A Linux SVG-based theme engine for Qt5/Qt6 and KDE
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt6Svg)
clang      : yes
optimize   : thin-lto
setup      : |
    # Fix Qt6 build with Qt5 installed
    sed -e 's|Qt6 Qt5|Qt6|' -i Kvantum/*/CMakeLists.txt
    # Build manager with Qt6
    sed -e 's|if(ENABLE_QT5)|if(TRUE)|' -i Kvantum/CMakeLists.txt

    %cmake_ninja -S Kvantum \
                 -B qt5-build \
                 -DENABLE_QT5=ON

    %cmake_ninja -S Kvantum \
                 -B qt6-build \
                 -DENABLE_QT5=OFF
build      : |
    %ninja_build -C qt5-build

    %ninja_build -C qt6-build
install    : |
    %ninja_install -C qt5-build

    %ninja_install -C qt6-build
