name       : qt6-speech
version    : 6.8.3
release    : 9
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtspeech-everywhere-src-6.8.3.tar.xz : b0dd3e3bf993e15dc03d3486ee1b452c2b92f0460a621eb32d261eecc040504b
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Speech Components
description: |
    The module enables a Qt application to support accessibility features such as text-to-speech, which is useful for end-users who are visually challenged or cannot access the application for whatever reason. The most common use case where text-to-speech comes in handy is when the end-user is driving and cannot attend the incoming messages on the phone. In such a scenario, the messaging application can read out the incoming message.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Qml)
    - pkgconfig(alsa)
    - pkgconfig(speech-dispatcher)
    # flite-devel # FIXME package this up
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples/
