name       : neovim-qt
version    : 0.2.19
release    : 17
source     :
    - https://github.com/equalsraf/neovim-qt/archive/refs/tags/v0.2.19.tar.gz : 2c5a5de6813566aeec9449be61e1a8cd8ef85979a9e234d420f2882efcfde382
homepage   : https://github.com/equalsraf/neovim-qt
license    : ISC
component  : editor
summary    : Neovim client library and GUI, in Qt5.
description: |
    Neovim client library and GUI, in Qt5.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(dri)
    - pkgconfig(msgpack-c)
    - neovim
rundeps    :
    - neovim
setup      : |
    %cmake . -B solusBuildDir \
      -DUSE_SYSTEM_MSGPACK=ON
build      : |
    pushd solusBuildDir
    %make
install    : |
    pushd solusBuildDir
    %make_install
    # Install AppStream metainfo
    install -Dm00644 $pkgfiles/io.github.equalsraf.neovim_qt.metainfo.xml -t $installdir/usr/share/metainfo
