name       : xdg-desktop-portal-gnome
version    : '47.3'
release    : 12
source     :
    - https://download.gnome.org/sources/xdg-desktop-portal-gnome/47/xdg-desktop-portal-gnome-47.3.tar.xz : 9f6e4b14b583367c915e9494764f27cb84927faa3f9e6e018b93bbbcf3361e44
homepage   : https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
description: |
    A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(xdg-desktop-portal)
    - gnome-keyring
rundeps    :
    - nautilus
    - xdg-desktop-portal-gtk
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
