name       : libspelling
version    : 0.4.4
release    : 3
source     :
    - https://download.gnome.org/sources/libspelling/0.4/libspelling-0.4.4.tar.xz : ac9132c634bb9df911e35b52345aa12126f7ec95e5f07179a980861819787150
homepage   : https://gitlab.gnome.org/GNOME/libspelling/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : A spellcheck library for GTK 4
description: |
    A spellcheck library for GTK 4
optimize   :
    - lto
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk4)
    - pkgconfig(gtksourceview-5)
    # pkgconfig(sysprof-capture-4)
    - vala
setup      : |
    %meson_configure -Dsysprof=false -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
