name       : python-orjson
version    : 3.10.16
release    : 49
source     :
    - https://files.pythonhosted.org/packages/source/o/orjson/orjson-3.10.16.tar.gz : d2aaa5c495e11d17b9b93205f5fa196737ee3202f000aaebf028dc9a73750f10
license    :
    - Apache-2.0
    - MIT
homepage   : https://github.com/ijl/orjson
component  : programming.python
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - python-installer
    - python-maturin
checkdeps  :
    - numpy
    - python-arrow
    - python-psutil
    - python-pytest
    - python-pytz
build      : |
    maturin build --release --strip
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
check      : |
    %python3_test pytest3
