name       : kwayland
version    : 6.3.4
release    : 101
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kwayland-6.3.4.tar.xz : a90848d5238ab75e706c96a535acbef5110441e92ffc9fc94336c69a1edf6835
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : programming.library
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-base-devel
clang      : yes
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
