name       : kwrited
version    : 6.3.4
release    : 116
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kwrited-6.3.4.tar.xz : f7b2cbe4bb7f795511a1f79727b0853395f20345faea2e4dafd34ab441c975b6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE daemon listening for wall and write messages
description: |
    KDE daemon listening for wall and write messages.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-knotifications-devel
    - kf6-kpty-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
