name       : kubo
version    : 0.34.1
release    : 34
source     :
    - https://github.com/ipfs/kubo/releases/download/v0.34.1/kubo-source.tar.gz : c2b02798f7e5b3b2c53b78100484929a7e2e72e5159b3bd8128cfe79573f0393
homepage   : https://ipfs.tech/
license    : MIT
component  : network.util
summary    : A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
description: |
    Kubo (go-ipfs) is the earliest and most widely used implementation of IPFS.

    IPFS is a global, versioned, peer-to-peer filesystem. It combines good ideas from previous systems such as Git, BitTorrent, Kademlia, SFS, and the Web. It is like a single BitTorrent swarm, exchanging git objects. IPFS provides an interface as simple as the HTTP web, but with permanence built-in. You can also mount the world at /ipfs.
replaces   :
    - go-ipfs
builddeps  :
    - git
    - golang
build      : |
    %make build
    ./cmd/ipfs/ipfs commands completion bash > ipfs-completion.bash
install    : |
    install -Dm00755 cmd/ipfs/ipfs $installdir/usr/bin/ipfs
    install -Dm00644 $pkgfiles/systemd/* -t $installdir/usr/lib/systemd/user/
    install -Dm00644 ipfs-completion.bash $installdir/usr/share/bash-completion/completions/ipfs
