name       : qt6-5compat
version    : 6.8.2
release    : 21
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.2/submodules/qt5compat-everywhere-src-6.8.2.tar.xz : b53154bc95ec08e2ddc266bef250fbd684b4eb2df96bc8c27d26b1e953495316
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
homepage   : https://www.qt.io
summary    : Qt 5 compatibility library for Qt 6
description: |
    The Qt 5 Core Compat module contains the Qt Core APIs which will be no longer supported in Qt 6 and therefore were removed from Qt 6. The module is provided to facilitate the transition to Qt 6.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(icu-i18n)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
