name       : qt6-5compat
version    : 6.8.3
release    : 22
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qt5compat-everywhere-src-6.8.3.tar.xz : 54b9c84bff34b423dd8c472862ce1009753ff505e418b4ef33907416da16b82e
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
homepage   : https://www.qt.io
summary    : Qt 5 compatibility library for Qt 6
description: |
    The Qt 5 Core Compat module contains the Qt Core APIs which will be no longer supported in Qt 6 and therefore were removed from Qt 6. The module is provided to facilitate the transition to Qt 6.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(icu-i18n)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
