name       : hwdata
version    : '0.394'
release    : 39
source     :
    - https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.394.tar.gz : b7c3fd7214a3b7c49d2661db127a712dc11cffd1799f793947aa1cb20aaf3298
homepage   : https://github.com/vcrhonek/hwdata/
license    : GPL-2.0-or-later
component  : system.base
summary    : Hardware identification and configuration data
description: |
    hwdata contains various hardware identification and configuration data, such as the pci.ids and usb.ids databases.
patterns   :
    - /*
setup      : |
    %configure
install    : |
    %make_install
