name       : libvte
version    : 0.78.3
release    : 72
source     :
    - https://download.gnome.org/sources/vte/0.78/vte-0.78.3.tar.xz : 97e2ac3a27bc5755358a223f55f5a2518654aa0361bfc61a196c1c2e08798eff
homepage   : https://gitlab.gnome.org/GNOME/vte
license    : LGPL-3.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(liblz4)
    - pkgconfig(libpcre2-8)
    - gi-docgen
    - gperf
    - libiconv-devel
    - vala
rundeps    :
    - devel :
        - pcre2-devel
patterns   :
    - docs :
        - /usr/share/doc/*
setup      : |
    %meson_configure -Ddocs=true -Dgtk4=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
