name       : qt6-location
version    : 6.8.3
release    : 10
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtlocation-everywhere-src-6.8.3.tar.xz : 1d05e95aa5b6bd26bffa004cd8c5c70ae2af649496010a1a70124293bc09fd43
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Location and Mapping Components
description: |
    The Qt Location API helps you create viable mapping solutions using the data available from some of the popular location services.
builddeps  :
    - pkgconfig(Qt6Positioning)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6ShaderTools)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
patterns   :
    - demos : /usr/lib64/qt6/examples
