name       : kinfocenter
version    : 6.3.4
release    : 125
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kinfocenter-6.3.4.tar.xz : 8ab78619f6c05e7162099d52ba83b0b5d11a3985cc4b0abf4112d91f815c2f69
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
builddeps  :
    - pkgconfig(libdisplay-info)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libusb-1.0)
    - aha
    - clinfo
    - dmidecode
    - fwupd
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kdoctools-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - mesa-demos
    - pciutils
    - vulkan-tools
    - wayland-utils
    - xdpyinfo
rundeps    :
    - aha
    - clinfo
    - dmidecode
    - fwupd
    - kf6-kirigami
    - libdisplay-info
    - mesa-demos
    - pciutils
    - plasma-disks
    - vulkan-tools
    - wayland-utils
    - xdpyinfo
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
    rm -rf $installdir/usr/share/doc
    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/icons/hicolor/128x128/apps/hwinfo.png
patterns   :
    - main :
        - /usr/lib64/libKInfoCenterInternal.so
