name       : kwayland-integration
version    : 6.3.4
release    : 119
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kwayland-integration-6.3.4.tar.xz : 46ca59835b8c924df616f331c1b33bd70784ddfdfdc50ab3f4bb8b944f04f8fd
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(KF5WaylandClient)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - kwindowsystem-devel
    - plasma-wayland-protocols-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
