name       : poco
version    : 1.14.0
release    : 8
source     :
    - https://github.com/pocoproject/poco/archive/refs/tags/poco-1.14.0-release.tar.gz : 48e98bbc8ed9fcd8bec43538402181d33cc2abe7e19ac8aea4bc113c9ba8ef89
license    : BSL-1.0
homepage   : https://pocoproject.org
component  :
    - programming.library
    - tools : programming.tools
summary    : C++ libraries for building network- and internet-based applications
description: |
    The POCO C++ Libraries are powerful cross-platform C++ libraries for building network- and internet-based applications that run on desktop, server, mobile, IoT, and embedded systems.
builddeps  :
    - pkgconfig(expat)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libutf8proc)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
patterns   :
    - tools : /usr/bin/*
setup      : |
    %apply_patches
    %cmake_ninja \
      -D POCO_UNBUNDLED=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
