name       : oxygen-sounds
version    : 6.3.4
release    : 26
source     :
    - https://download.kde.org/stable/plasma/6.3.4/oxygen-sounds-6.3.4.tar.xz : 49ceec138a20157d5f1625d474d616c48cc052705b1059c1763c8c1579862065
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.theme
summary    : The Oxygen Sound Theme
description: The Oxygen Sound Theme
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
