name       : python-aiohttp
version    : 3.11.14
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.11.14.tar.gz : d6edc538c7480fa0a3b2bdd705f8010062d74700198da55d16498e1b49549b9c
homepage   : https://docs.aiohttp.org/
license    : Apache-2.0
component  : programming.python
summary    : Asynchronous HTTP client/server framework for asyncio and Python
description: |
    Asynchronous HTTP client/server framework for asyncio and Python
builddeps  :
    - cython
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-aiohappyeyeballs
    - python-aiosignal
    - python-attrs
    - python-frozenlist
    - python-propcache
    - python-yarl
build      : |
    %python3_setup
install    : |
    %python3_install
