name       : plasma-systemmonitor
version    : 6.3.4
release    : 57
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-systemmonitor-6.3.4.tar.xz : 99d7c42912681172e304958fb1d330cecc6ce95db8a0336953ff2b4d0c65ac5d
homepage   : https://kde.org/plasma-desktop
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
libsplit   : no
builddeps  :
    - kf6-kdbusaddons-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - kirigami-addons-devel
    - ksystemstats
    - libksysguard-devel
rundeps    :
    - kf6-kiconthemes
    - kf6-kirigami
    - kirigami-addons
    - ksystemstats
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
