name       : qt6-virtualkeyboard
version    : 6.8.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtvirtualkeyboard-everywhere-src-6.8.3.tar.xz : 8111061261ed8d88ec40b79083f8ed025650eb1807a05528615265d36213bb1d
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt Virtual Keyboard
description: |
    Qt Virtual Keyboard is a virtual keyboard framework that consists of a C++ backend supporting custom input methods as well as a UI frontend implemented in QML.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
    - pkgconfig(hunspell)
rundeps    :
    - devel :
        - libhunspell-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
