name       : systemsettings
version    : 6.3.4
release    : 121
source     :
    - https://download.kde.org/stable/plasma/6.3.4/systemsettings-6.3.4.tar.xz : 234ca17d05a5d09c1570e1d935fd03da2dd4ce53c5b7545ba436a56ad4b9ef83
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(KF6GuiAddons)
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-krunner-devel
    - plasma-activities-devel
rundeps    :
    - flatpak-kcm
    - kf6-kirigami
    - wacomtablet
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc
