name       : qt6-languageserver
version    : 6.8.3
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtlanguageserver-everywhere-src-6.8.3.tar.xz : e4d320073c55b3a418a784e7866c43bc3e3d52817368be56e7d468866ff8b469
license    : GPL-3.0-or-later
component  : desktop.qt
homepage   : https://www.qt.io
summary    : An implementation of the Language Server Protocol
description: |
    An implementation of the Language Server Protocol
builddeps  :
    - pkgconfig(Qt6Core)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-solus-Build-libs-shared.patch

    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
