name       : gnome-terminal
version    : 3.54.4
release    : 63
source     :
    - https://download.gnome.org/sources/gnome-terminal/3.54/gnome-terminal-3.54.4.tar.xz : 443a80689337108e4b190399969e66aba041cc3c63bb99c5738525d528b132b8
homepage   : https://gitlab.gnome.org/GNOME/gnome-terminal
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : GNOME Terminal Emulator
description: |
    GNOME Terminal Emulator
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnautilus-extension-4)
    - pkgconfig(libpcre2-8)
    - pkgconfig(vte-2.91)
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools
setup      : |
    %patch -p1 -i $pkgfiles/0001-Enforce-Solus-Defaults.patch

    %meson_configure -Dsearch_provider=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    # NOTE: try removing this for gnome 48 and see what breaks
    ln -sv gnome-terminal $installdir/usr/bin/x-terminal-emulator
