name       : kicad-footprints
version    : 9.0.1
release    : 13
source     :
    - https://gitlab.com/kicad/libraries/kicad-footprints/-/archive/9.0.1/kicad-footprints-9.0.1.tar.gz : 48a51a97dd99a8196d8f8fa861bae499f7b28760b0d1716e914a25d6003d9bb7
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad Footprint Libraries
description: |
    The libraries are intended to be used with KiCad.
setup      : |
    %cmake
install    : |
    %make_install
