name       : glaze
version    : 5.0.2
release    : 2
source     :
    - https://github.com/stephenberry/glaze/archive/refs/tags/v5.0.2.tar.gz : ed47ba0b5dcef5a2d2a41b4863e91a3b509c469a70c1a1fed885545d1b672681
homepage   : https://github.com/stephenberry/glaze
license    : MIT
component  : programming.library
summary    : Extremely fast, in memory, JSON and interface library for modern C++
description: |
    Extremely fast, in memory, JSON and interface library for modern C++
networking : yes
builddeps  :
    - git
patterns   :
    - /usr/*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
