name       : gnome-online-accounts
version    : 3.52.3.1
release    : 54
source     :
    - https://download.gnome.org/sources/gnome-online-accounts/3.52/gnome-online-accounts-3.52.3.1.tar.xz : 49ed727d6fc49474996fa7edf0919b21e4fc856ea37e6e30f17b50b103af9701
homepage   : https://gnome.pages.gitlab.gnome.org/gnome-online-accounts/
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts
description: |
    GNOME Online Accounts is a single sign-on framework for GNOME. It aims to provide a way for users to setup online accounts to be used by the core system and core applications only.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gcr-4)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libkeyutils)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-1.0)
    - docbook-xml
    - vala
setup      : |
    %meson_configure -Ddocumentation=false
build      : |
    %ninja_build
install    : |
    %ninja_install
