name       : kgamma
version    : 6.3.4
release    : 28
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kgamma-6.3.4.tar.xz : fc3c61b1eea0807ff0471e4e89cb0efa0bf8b710933e159f794050982d9e4ddb
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(xxf86vm)
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc
replaces   :
    - kgamma5
    - dbginfo : kgamma5-dbginfo
