name       : kscreen
version    : 6.3.4
release    : 118
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kscreen-6.3.4.tar.xz : 99af84cb5b8e14a8945dfff20e7acd4245cae9f1c7cd311f3eee8dd22c100b25
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(KF6Screen)
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(Qt6Sensors)
    - pkgconfig(xcb-atom)
    - pkgconfig(xi)
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-ksvg-devel
    - layer-shell-qt-devel
    - libplasma-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
