name       : plasma-workspace-wallpapers
version    : 6.3.4
release    : 28
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-workspace-wallpapers-6.3.4.tar.xz : ca3d7049da92de3befb6a905d426e393460facfb091df984f6ae61f0eeca8c49
homepage   : https://kde.org/plasma-desktop
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.kde
summary    : Wallpapers for Plasma Workspaces
description: |
    Wallpapers for Plasma Workspaces
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
