name       : libfido2
version    : 1.15.0
release    : 9
source     :
    - https://github.com/Yubico/libfido2/archive/refs/tags/1.15.0.tar.gz : 32e3e431cfe29b45f497300fdb7076971cb77fc584fcfa80084d823a6ed94fbb
license    : BSD-2-Clause
component  : system.base
homepage   : https://developers.yubico.com/libfido2/
summary    : Library functionality for FIDO 2.0
description: |
    libfido2 provides library functionality and command-line tools to communicate with a FIDO device over USB, and to verify attestation and assertion signatures.
    libfido2 supports the FIDO U2F (CTAP 1) and FIDO 2.0 (CTAP 2) protocols.
builddeps  :
    - pkgconfig(libcbor)
    - pkgconfig(libpcsclite)
setup      : |
    %cmake_ninja -DBUILD_STATIC_LIBS=OFF -DBUILD_EXAMPLES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
