name       : qt6-connectivity
version    : 6.8.3
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtconnectivity-everywhere-src-6.8.3.tar.xz : 477176383308ce77f974a16f118027e833061caed57aeb30eeb4306a583c9b39
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 Connectivity components
description: |
    Qt connectivity provides access to Bluetooth hardware.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(bluez)
    - pkgconfig(libpcsclite)
rundeps    :
    - devel :
        - bluez-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
