name       : hyprutils
version    : 0.5.2
release    : 7
source     :
    - https://github.com/hyprwm/hyprutils/archive/refs/tags/v0.5.2.tar.gz : b30b93be9597489bd5a29c8cd91d60ea0fcaea08fd03cca1368e101c4ae19d3d
homepage   : https://github.com/hyprwm/hyprutils
license    : BSD-3-Clause
component  : desktop.hyprland
summary    : Small C++ library for the Hypr* ecosystem.
description: |
    Hyprutils is a small C++ library for utilities used across the Hypr* ecosystem.
builddeps  :
    - pkgconfig(pixman-1)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
