name       : qt6-positioning
version    : 6.8.3
release    : 13
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtpositioning-everywhere-src-6.8.3.tar.xz : 6ab69a7e71a7795aab9ca2798eea126e36df55159a771ebd2f37cad3da63e9d3
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 position, satellite and area monitoring classes
description: |
    Provides access to position, satellite and area monitoring classes
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6SerialPort)
    - pkgconfig(Qt6Svg)
    - pkgconfig(gconf-2.0)
rundeps    :
    - devel :
        - gconf-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt6/bin
    - demos :
        - /usr/lib64/qt6/examples
