name       : yt-dlp
version    : 2025.03.26
release    : 243
source     :
    - https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2025.03.26.tar.gz : f91b7cd8e58d538e90855fee2e24c34c5f78668a28889c388ed293ce4089b78c
license    : Unlicense
component  : network.download
homepage   : https://github.com/yt-dlp/yt-dlp
summary    : yt-dlp is a small command-line program for downloading videos from YouTube and other platforms
description: |
    yt-dlp, a fork of youtube-dl, is a small command-line program for downloading videos from YouTube and other platforms
replaces   :
    - youtube-dl
    - yt-dlc
builddeps  :
    - pkgconfig(python3)
    - pandoc
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - mutagen
    - python-certifi
    - python-pycryptodome
    - python-websockets
    - python3
build      : |
    %make PREFIX=$installdir/usr yt-dlp.1 completion-bash completion-fish completion-zsh
    python3 -m build --wheel --no-isolation
install    : |
    python3 -m installer --destdir="$installdir" dist/*.whl
    rm -rf $installdir/usr/share/doc
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/youtube-dl
    ln -s /usr/bin/yt-dlp $installdir/usr/bin/yt-dlc
