name       : qt6-serialport
version    : 6.8.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtserialport-everywhere-src-6.8.3.tar.xz : c164a0392dc7cab3d072fa8fdcacc8fc4f3e685234b021b3128020719cdf5fa5
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 Serial Port Module
description: |
    Qt6 Serial Port provides the basic functionality, which includes configuring, I/O operations, getting and setting the control signals of the RS-232 pinouts.
builddeps  :
    - pkgconfig(Qt6Core)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
