name       : ptyxis
version    : '47.8'
release    : 5
source     :
    - https://download.gnome.org/sources/ptyxis/47/ptyxis-47.8.tar.xz : b494035aea4c29994520154400fef2fc97d789757b8cafdcb3b1f65cd00d602d
homepage   : https://devsuite.app/ptyxis/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A terminal for a container-oriented desktop
description: |
    Ptyxis is a terminal for GNOME that focuses on ease-of-use in a world of containers.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(vte-2.91)
    - desktop-file-utils
setup      : |
    %meson_configure -Dgeneric=terminal
build      : |
    %ninja_build
install    : |
    %ninja_install
