name       : gnome-keyring
version    : '46.2'
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-keyring/46/gnome-keyring-46.2.tar.xz : bf26c966b8a8b7f3285ecc8bb3e467b9c20f9535b94dc451c9c559ddcff61925
homepage   : https://gitlab.gnome.org/GNOME/gnome-keyring
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome
summary    : GNOME Keyring is a collection of components in GNOME that store secrets, passwords, keys, certificates and make them available to applications.
description: |
    GNOME Keyring is a collection of components in GNOME that store secrets, passwords, keys, certificates and make them available to applications. GNOME Keyring is integrated with the user's login, so that their secret storage can be unlocked when the user logins into their session. GNOME Keyring is based around a standard called PKCS#11, which is a standard way for applications to manage certificates and keys on smart cards or secure storage.
builddeps  :
    - pkgconfig(gck-1)
    - pkgconfig(gcr-4)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgcrypt)
    - pkgconfig(p11-kit-1)
    - docbook-xml
    - openssh
setup      : |
    %configure --disable-doc --disable-static \
               --without-libcap-ng \
               --with-pam-dir=%libdir%/security \
               --enable-ssh-agent
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
