name       : kpipewire
version    : 6.3.4
release    : 42
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kpipewire-6.3.4.tar.xz : bbfd42737b5968fbc855e974aa68739e87ccd24b0a6e23d71afc0e98a9115458
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Components relating to pipewire use in Plasma
description: |
    Components relating to pipewire use in Plasma
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libavcodec)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libva)
    - extra-cmake-modules
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
rundeps    :
    - devel :
        # For epoxy/egl.h
        - libepoxy-devel
        - pipewire-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
