name       : print-manager
version    : 6.3.4
release    : 104
source     :
    - https://download.kde.org/stable/plasma/6.3.4/print-manager-6.3.4.tar.xz : 5b32d535c020a38c80bad952a1ada764ad1ea20dc5dc2bb5f4a034a9c6c76a61
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
libsplit   : no
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(cups)
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - libplasma-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-Don-t-build-with-soname.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
