name       : gnome-text-editor
version    : '47.4'
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-text-editor/47/gnome-text-editor-47.4.tar.xz : 3ac505a904aafce353813bb13a7b8f82a39d474c4a945ce89aef7e650ec9f8da
homepage   : https://apps.gnome.org/TextEditor/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A simple text editor for the GNOME desktop.
description: |
    GNOME Text Editor is a simple text editor focused on a pleasing default experience.
optimize   :
    - lto
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(gtk4)
    - pkgconfig(gtksourceview-5)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libspelling-1)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
