name       : milou
version    : 6.3.4
release    : 117
source     :
    - https://download.kde.org/stable/plasma/6.3.4/milou-6.3.4.tar.xz : ae7bd7d22e66e588034fe21a73aa8b376d233e82f44470707b708c1771e3ff37
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(Qt6Qml)
    - kf6-kconfig-devel
    - kf6-ki18n-devel
    - kf6-krunner-devel
    - kf6-ksvg-devel
    - libplasma-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
