name       : qt6-datavis3d
version    : 6.8.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtdatavis3d-everywhere-src-6.8.3.tar.xz : 8323b6d4ad719b9332343760de27f0e8511f75bc2b8750c7821b08988585fe1a
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 Data Visualization module
description: |
    Qt Data Visualization module provides multiple graph types to visualize data in 3D space both with C++ and QML.
builddeps  :
    - pkgconfig(Qt6Qml)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
