name       : ocean-sound-theme
version    : 6.3.4
release    : 27
source     :
    - https://download.kde.org/stable/plasma/6.3.4/ocean-sound-theme-6.3.4.tar.xz : 06317dac665aec586d2141237ac6c898d401c5659a4f0d98548b6b9019c4a1ec
homepage   : https://kde.org/plasma-desktop
license    :
    - BSD-2-Clause
    - CC-BY-SA-4.0
    - CC0-1.0
component  : desktop
summary    : Ocean Sound Theme for Plasma
description: |
    Ocean Sound Theme for Plasma
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
