name       : sddm-kcm
version    : 6.3.4
release    : 114
source     :
    - https://download.kde.org/stable/plasma/6.3.4/sddm-kcm-6.3.4.tar.xz : 6dbaafdfd5d8293f6dd90c86594a975a8d1c3af07fa0711044a8aae2cba91743
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(xcb-cursor)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
