name       : kglobalacceld
version    : 6.3.4
release    : 28
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kglobalacceld-6.3.4.tar.xz : 827d136e1912b62490264bfe6c03ce4e9d9d00773e72d377fce23f00bf70ead9
homepage   : https://kde.org/plasma-desktop/
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Daemon providing Global Keyboard Shortcut (Accelerator) functionality
description: |
    Daemon providing Global Keyboard Shortcut (Accelerator) functionality
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(Qt6Core)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-record)
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kjobwidgets-devel
    - kf6-kservice-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
