name       : plasma-sdk
version    : 6.3.4
release    : 101
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-sdk-6.3.4.tar.xz : aea52ef5905552d5242e8974d2f9e053445764650bc263bb0f35ee43a5cb09cc
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - kf6-karchive-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-kpackage-devel
    - kf6-ksvg-devel
    - kf6-ktexteditor-devel
    - kf6-kxmlgui-devel
    - libplasma-devel
    - plasma5support-devel
runtime    :
    - kf6-kirigami
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
