name       : qt6-serialbus
version    : 6.8.3
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtserialbus-everywhere-src-6.8.3.tar.xz : 43480eeb7172757d2af2c5717cfed84a9254bef775cd715fd27258a81c7b7e9e
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt module for general purpose serial bus access
description: |
    Qt module for general purpose serial bus access
builddeps  :
    - pkgconfig(Qt6SerialPort)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
