name       : libadwaita
version    : 1.6.5
release    : 26
source     :
    - https://download.gnome.org/sources/libadwaita/1.6/libadwaita-1.6.5.tar.xz : d4713cfe5daeb2e537ccb6cb013c153677a3f1c29e5c166c5663e33605eb8ee2
homepage   : https://gnome.pages.gitlab.gnome.org/libadwaita/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Building blocks for modern adaptive GNOME applications.
description: |
    Adwaita offers application developers many widgets and objects to build GNOME applications scaling from desktop workstations to mobile phones.
optimize   :
    - lto
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - sassc
    - vala
setup      : |
    %meson_configure -Dexamples=false
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
