name       : plasma-browser-integration
version    : 6.3.4
release    : 102
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-browser-integration-6.3.4.tar.xz : f8c2b983d0c94b8ab990a0e20afb949b0ef69f2b9b7e1764b676ad0c41a1ed70
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-3.0-or-later
component  : desktop.kde.core
summary    : Integrate browsers into the Plasma Desktop
description: |
    Components necessary to integrate browsers into the Plasma Desktop.
builddeps  :
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kfilemetadata-devel
    - kf6-ki18n-devel
    - kf6-kio-devel
    - kf6-kjobwidgets-devel
    - kf6-knotifications-devel
    - kf6-krunner-devel
    - kf6-kservice-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-purpose-devel
    - plasma-activities-devel
    - plasma-workspace-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6 -DINSTALL_CHROME_MANIFEST=ON \
               -DMOZILLA_DIR=%libdir%/mozilla
build      : |
    %ninja_build
install    : |
    %ninja_install
