name       : qt6-quick3d
version    : 6.8.3
release    : 16
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtquick3d-everywhere-src-6.8.3.tar.xz : 30483c700e521b9bc53a5f68cbaed089416c991fc29f5fb4179cde53fd3652df
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 Quick 3D module
description: |
    Qt Quick 3D provides a high-level API for creating 3D content and 3D user interfaces based on Qt Quick. Rather than using an external engine which creates syncing issues, and additional layers of abstraction, we provide extensions to the existing Qt Quick Scene Graph for spatial content, and a renderer for that extended scene graph. When using the spatial scene graph it is also possible to mix Qt Quick 2D content with 3D content.
builddeps  :
    - pkgconfig(Qt6QuickTemplates2)
    - pkgconfig(Qt6QuickTimeline)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(assimp)
rundeps    :
    - devel :
        - assimp-devel
        - qt6-quicktimeline-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt6/bin
        - /usr/lib64/qt6/plugins/qmltooling/
    - demos :
        - /usr/lib64/qt6/examples
