name       : polychromatic
version    : 0.9.4
release    : 26
source     :
    - https://github.com/polychromatic/polychromatic/archive/refs/tags/v0.9.4.tar.gz : aa1a8b2a8f6ce0207298965ed829c88621b7abc5fcf6fe48705a91f47a95faf9
license    : GPL-3.0-or-later
component  : system.utils
networking : yes
homepage   : https://polychromatic.app
summary    : Graphical front end and tray applet for configuring Razer peripherals
description: |
    A front-end for customising the functionality of your Razer perpherials.
builddeps  :
    - sassc
rundeps    :
    - imagemagick
    - libayatana-appindicator
    - openrazer-current
    - python-colorama
    - python-colour
    - python-gobject
    - python-pyqt6-webengine
    - python-qt6
    - python-requests
    - python-setproctitle
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Move to stateless path
    install -Dm00644 $installdir/etc/xdg/autostart/polychromatic-autostart.desktop -t $installdir/usr/share/xdg/autostart/
    rm -v $installdir/etc/xdg/autostart/polychromatic-autostart.desktop
    rmdir -v $installdir/etc/xdg/autostart/ \
             $installdir/etc/xdg/ \
             $installdir/etc/
