name       : xdg-desktop-portal-kde
version    : 6.3.4
release    : 107
source     :
    - https://download.kde.org/stable/plasma/6.3.4/xdg-desktop-portal-kde-6.3.4.tar.xz : 59c62f679d2dac721dd537d83ad3075c129d07e1056e0a592117f711979f0821
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(KF6GuiAddons)
    - pkgconfig(KWaylandClient)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(cups)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - kf6-kcrash-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kio-fuse
    - plasma-wayland-protocols-devel
rundeps    :
    - kio-fuse
    - xdg-desktop-portal
    # Needed so that GTK flatpaks respect system settings
    - xdg-desktop-portal-gtk
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
