name       : plasma-vault
version    : 6.3.4
release    : 90
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-vault-6.3.4.tar.xz : de77af74e09c9539edcf6308ee45e028309905bea08e24f5ff985977e9f86c62
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(libnm)
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-kitemmodels-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
rundeps    :
    - cryfs
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
