name       : mdbook
version    : 0.4.48
release    : 44
source     :
    - https://github.com/rust-lang/mdBook/archive/refs/tags/v0.4.48.tar.gz : 65021ceca2a2f5a1ceda243953ce764bf34c466b7a83db38e167a2b7d1131dcf
homepage   : https://github.com/rust-lang/mdBook
license    : MPL-2.0
component  : programming.tools
summary    : Create books from markdown files
description: |
    mdBook is a command line tool to create book from markdown files. Like Gitbook but implemented in Rust.
networking : yes
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
