name       : gnome-recipes
version    : 2.0.4
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-recipes/2.0/gnome-recipes-2.0.4.tar.xz : b30e96985f66fe138a17189c77af44d34d0b4c859b304ebdb52033bc2cd3ffed
homepage   : https://gitlab.gnome.org/GNOME/recipes/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : An easy-to-use application that will help you to discover what to cook today, tomorrow, the rest of the week and for your special occasions
description: |
    An easy-to-use application that will help you to discover what to cook today, tomorrow, the rest of the week and for your special occasions.
builddeps  :
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(rest-0.7)
    - git
    - itstool
environment: |
    export CFLAGS="${CFLAGS} -Wno-incompatible-pointer-types"
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
