name       : kactivitymanagerd
version    : 6.3.4
release    : 117
source     :
    - https://download.kde.org/stable/plasma/6.3.4/kactivitymanagerd-6.3.4.tar.xz : 4f50b5e57f83b28a888393186348477644877b889c300651e0e06dd77ee97502
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
builddeps  :
    - kf6-kcrash-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libboost-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
