name       : qt6-3d
version    : 6.8.3
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qt3d-everywhere-src-6.8.3.tar.xz : 095e1be77ffd4b158d9e57f16ee898caf7d0d6e5406f466d9d8315d5b1e79563
homepage   : https://doc.qt.io/qt-6/qt3d-overview.html
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 3D module
description: |
    Qt 3D provides functionality for near-realtime simulation systems with support for 2D and 3D rendering in both Qt C++ and Qt Quick applications.
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(assimp)
rundeps    :
    - devel :
        - assimp-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
