name       : qt6-quicktimeline
version    : 6.8.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtquicktimeline-everywhere-src-6.8.3.tar.xz : b2ba57fa4fb929d3cd103dff65dd7a62dc2e3852f9a4fddd081e4a759b684fdd
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
homepage   : https://www.qt.io
summary    : Enables keyframe-based animations and parameterization for Qt6
description: |
    The Qt Quick Timeline module enables keyframe-based animations and parameterization. This module is directly supported by Qt Design Studio and Qt Quick Designer, with a timeline editor to create keyframe-based animations.
builddeps  :
    - pkgconfig(Qt6Qml)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
