name       : plasma-pa
version    : 6.3.4
release    : 120
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-pa-6.3.4.tar.xz : 2bb964e29b7a37f2a5b3787ce573347a9adbfb889eba49c99404be444f5e9b99
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
builddeps  :
    - pkgconfig(KF6PulseAudioQt)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - kf6-kcmutils-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ksvg-devel
    - kirigami-addons-devel
    - libplasma-devel
    - sound-theme-freedesktop
rundeps    :
    - kf6-kirigami
    - kf6-kitemmodels
    - kirigami-addons
    - sound-theme-freedesktop
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
    rm -rfv $installdir/usr/share/doc
