name       : libluv
version    : 1.50.0
release    : 10
source     :
    - https://github.com/luvit/luv/releases/download/1.50.0-1/luv-1.50.0-1.tar.gz : d867c3024d9c981d54f2edd83e13fd6dc1158f0608635f7b1c0f6b5586b5bc34
homepage   : https://github.com/luvit/luv
license    : Apache-2.0
component  : programming
summary    : Bare libuv bindings for lua
description: |
    Makes libuv available to lua scripts. It was made for the luvit project but should usable from nearly any lua project.
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(luajit)
setup      : |
    %cmake_ninja \
      -DBUILD_MODULE=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DLUA_BUILD_TYPE=System \
      -DWITH_SHARED_LIBUV=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
