name       : ksshaskpass
version    : 6.3.4
release    : 116
source     :
    - https://download.kde.org/stable/plasma/6.3.4/ksshaskpass-6.3.4.tar.xz : 793341db12cf38ecece998ccbbb685871be5e5099ae6c886872279433a255995
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kwallet-devel
    - kf6-kwidgetsaddons-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
