name       : qt6gtk2
version    : '0.3'
release    : 12
source     :
    - https://github.com/trialuser02/qt6gtk2/releases/download/0.3/qt6gtk2-0.3.tar.xz : 386d0665558f1ac7ec318f2741dd762ca8c9a4a071a2c5f181212641ad0658b3
homepage   : https://github.com/trialuser02/qt6gtk2
license    : GPL-2.0-or-later
component  : desktop.qt
summary    : GTK+2.0 integration plugins for Qt6
description: |
    Qt6Gtk2 - GTK+2.0 integration plugins for Qt6.
builddeps  :
    - pkgconfig(Qt6UiTools)
    - pkgconfig(gtk+-2.0)
clang      : yes
setup      : |
    /usr/lib/qt6/bin/qmake PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
