name       : libksysguard
version    : 6.3.4
release    : 118
source     :
    - https://download.kde.org/stable/plasma/6.3.4/libksysguard-6.3.4.tar.xz : 04c1ee8b1a174ad5f8d6f1e2d42eeb93079b2f3856badcb8cb53e1f9d7cb15dc
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcap)
    - pkgconfig(xres)
    - kf6-kauth-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - lm_sensors-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
