name       : qt6-webview
version    : 6.8.3
release    : 9
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtwebview-everywhere-src-6.8.3.tar.xz : 2c46e472034c8a254bb4dbd15250a3fa8f727135a14718a3ff1175697b487ed2
license    :
    - LGPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 WebView Library
description: |
    Qt WebView provides a way to display web content in a QML application without necessarily including a full web browser stack by using native APIs where it makes sense.
clang      : yes
optimize   :
    - speed
    - thin-lto
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6WebEngineCore)
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
