name       : gnome-mahjongg
version    : '48.0'
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-mahjongg/48/gnome-mahjongg-48.0.tar.xz : aeb16f4c940bdb6a670c7d9acdd50dd0ec20b321bd7075a985891fbbebcd4fed
homepage   : https://gitlab.gnome.org/GNOME/gnome-mahjongg/
license    : GPL-2.0-or-later
component  : games.card
summary    : Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
