name       : darkly
version    : 0.5.18
release    : 1
source     :
    - https://github.com/Bali10050/Darkly/archive/refs/tags/v0.5.18.tar.gz : f457ad77f344def425ae26f8f8484249a238170ac73f57e556207d0e3355cf0c
homepage   : https://github.com/Bali10050/Darkly
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : A modern style for qt6 applications.
description: |
    Fork of Lightly (A modern style for Qt applications)
builddeps  :
    - cmake
    - extra-cmake-modules
    - git
    - hicolor-icon-theme
    - kdecoration-devel
    - kf6-frameworkintegration-devel
    - kf6-kcmutils-devel
    - kf6-kcolorscheme-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kirigami-devel
    - kf6-kwindowsystem-devel
    - qt6-declarative-devel
setup      : |
    %cmake_ninja -DBUILD_QT6=ON -DBUILD_QT5=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
