name       : plasma-thunderbolt
version    : 6.3.4
release    : 79
source     :
    - https://download.kde.org/stable/plasma/6.3.4/plasma-thunderbolt-6.3.4.tar.xz : 45566a03de123b9b470bb5f35a542a16e005e4ea83fad57391c21cdc38d4bcb0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma integration for controlling Thunderbolt devices
description: |-
    Plasma integration for controlling Thunderbolt devices
libsplit   : no
builddeps  :
    - bolt
    - kf6-kcmutils-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-knotifications-devel
rundeps    :
    - bolt
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
