name       : ansible
version    : 2.18.4
release    : 58
source     :
    - https://github.com/ansible/ansible/archive/refs/tags/v2.18.4.tar.gz : d360405b5799090f2aab5f41f68543419020ba8243b20088260f6b6081b72bc5
license    : GPL-3.0-or-later
homepage   : https://www.ansible.com/
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-build
    - python-docutils
    - python-installer
    - python-jinja
rundeps    :
    - python-jinja
    - python-jmespath
    - python-paramiko
    - python-resolvelib
    - pyyaml
setup      : |
    %patch -p1 -i $pkgfiles/bump_resolvelib_upper_version_bound.patch
build      : |
    %python3_setup
install    : |
    %python3_install
