name       : nvme-cli
version    : '2.12'
release    : 24
source     :
    - https://github.com/linux-nvme/nvme-cli/archive/refs/tags/v2.12.tar.gz : bb6528d0528ccf5d05fbe8e90b82b7632cc0896ffcbe2f4c823ff2de1e79693e
homepage   : https://github.com/linux-nvme/nvme-cli
license    : GPL-2.0-only
component  : system.utils
summary    : NVM-Express user space tooling for Linux.
description: |
    NVM-Express user space tooling for Linux.
builddeps  :
    - pkgconfig(libnvme)
setup      : |
    %meson_configure \
        -Dudevrulesdir=lib64/udev/rules.d \
        -Dsystemddir=lib/systemd/system \
        -Ddocs=man
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove default/example config
    rm -rv $installdir/etc/
