name       : ksystemstats
version    : 6.3.4
release    : 53
source     :
    - https://download.kde.org/stable/plasma/6.3.4/ksystemstats-6.3.4.tar.xz : 00006a9370d03a1114c31a869c6c0676c4493aac3716138dd9aea898d0e85395
homepage   : https://invent.kde.org/plasma/ksystemstats
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - kf6-kcrash-devel
    - kf6-kio-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - lm_sensors-devel
rundeps    :
    - libksysguard
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
