name       : qt6-lottie
version    : 6.8.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtlottie-everywhere-src-6.8.3.tar.xz : d732e754497a1295c4f512312828a11551fe89433259af9ee9f1e62bb7263d24
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
homepage   : https://www.qt.io
summary    : Qt6 Lottie Animation module
description: |
    Qt Lottie Animation provides a QML API for rendering graphics and animations that are exported in JSON format.
builddeps  :
    - pkgconfig(Qt6Qml)
rundeps    :
    - devel :
        - qt6-declarative-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
