name       : qt6-sensors
version    : 6.8.3
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtsensors-everywhere-src-6.8.3.tar.xz : b871a7501f9fa609f35260ea39a0f198427d6d6b9ee8d1a6ddb987cc26511eae
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 Sensors Module
description: |
    The Qt Sensors API provides access to sensor hardware via QML and C++ interfaces. The Qt Sensors API also provides a motion gesture recognition API for devices.
builddeps  :
    - pkgconfig(Qt6Bluetooth)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
