name       : zoxide
version    : 0.9.7
release    : 4
source     :
    - https://github.com/ajeetdsouza/zoxide/archive/refs/tags/v0.9.7.tar.gz : d93ab17a01de68529ef37b599524f882dc654835cc121a9097dd3f2952fd207e
homepage   : https://github.com/ajeetdsouza/zoxide
license    : MIT
component  : programming.tools
summary    : A smarter cd command. Supports all major shells.
description: |
    A smarter cd command. Supports all major shells.
networking : yes
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install

    install -d $installdir/usr/share/{man/man1,doc/zoxide,zsh/site-functions,fish/vendor_completions.d,bash-completion/completions/zoxide}
    install -Dm00644 man/man1/*.1 $installdir/usr/share/man/man1/
    install -Dm00644 README.md $installdir/usr/share/doc/zoxide/

    cd contrib/completions
    install -Dm00644 _zoxide $installdir/usr/share/zsh/site-functions/
    install -Dm00644 zoxide.fish $installdir/usr/share/fish/vendor_completions.d/
    install -Dm00644 zoxide.bash $installdir/usr/share/bash-completion/completions/zoxide
