name       : python-proton-vpn-local-agent
version    : 1.4.4
release    : 2
source     :
    - https://github.com/ProtonVPN/local-agent-rs/archive/refs/tags/1.4.4.tar.gz : 482234a68b0ccb8f898c77821bbad8703215a0880aa920dea583cbd0fe002d4e
homepage   : https://github.com/ProtonVPN/local-agent-rs
license    : GPL-3.0-or-later
component  : programming.python
summary    : Proton VPN local agent written in Rust
description: |
    Proton VPN local agent written in Rust
networking : yes
builddeps  :
    - rust
setup      : |
    pushd $workdir/python-proton-vpn-local-agent
    %cargo_fetch
    popd
build      : |
    pushd $workdir/python-proton-vpn-local-agent
    %cargo_build
    popd
install    : |
    install -Dm00755 $workdir/python-proton-vpn-local-agent/target/release/libpython_proton_vpn_local_agent.so $installdir/usr/lib/python3.11/site-packages/proton/vpn/local_agent.abi3.so
